//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ./KotlinParser.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace CobbleBuild.Kotlin {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="KotlinParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IKotlinParserListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.kotlinFile"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterKotlinFile([NotNull] KotlinParser.KotlinFileContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.kotlinFile"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitKotlinFile([NotNull] KotlinParser.KotlinFileContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.script"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterScript([NotNull] KotlinParser.ScriptContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.script"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitScript([NotNull] KotlinParser.ScriptContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.shebangLine"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterShebangLine([NotNull] KotlinParser.ShebangLineContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.shebangLine"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitShebangLine([NotNull] KotlinParser.ShebangLineContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.fileAnnotation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFileAnnotation([NotNull] KotlinParser.FileAnnotationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.fileAnnotation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFileAnnotation([NotNull] KotlinParser.FileAnnotationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.packageHeader"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPackageHeader([NotNull] KotlinParser.PackageHeaderContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.packageHeader"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPackageHeader([NotNull] KotlinParser.PackageHeaderContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.importList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImportList([NotNull] KotlinParser.ImportListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.importList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImportList([NotNull] KotlinParser.ImportListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.importHeader"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImportHeader([NotNull] KotlinParser.ImportHeaderContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.importHeader"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImportHeader([NotNull] KotlinParser.ImportHeaderContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.importAlias"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImportAlias([NotNull] KotlinParser.ImportAliasContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.importAlias"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImportAlias([NotNull] KotlinParser.ImportAliasContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.topLevelObject"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTopLevelObject([NotNull] KotlinParser.TopLevelObjectContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.topLevelObject"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTopLevelObject([NotNull] KotlinParser.TopLevelObjectContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.typeAlias"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeAlias([NotNull] KotlinParser.TypeAliasContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.typeAlias"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeAlias([NotNull] KotlinParser.TypeAliasContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclaration([NotNull] KotlinParser.DeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclaration([NotNull] KotlinParser.DeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.classDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassDeclaration([NotNull] KotlinParser.ClassDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.classDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassDeclaration([NotNull] KotlinParser.ClassDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.primaryConstructor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimaryConstructor([NotNull] KotlinParser.PrimaryConstructorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.primaryConstructor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimaryConstructor([NotNull] KotlinParser.PrimaryConstructorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.classBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassBody([NotNull] KotlinParser.ClassBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.classBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassBody([NotNull] KotlinParser.ClassBodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.classParameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassParameters([NotNull] KotlinParser.ClassParametersContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.classParameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassParameters([NotNull] KotlinParser.ClassParametersContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.classParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassParameter([NotNull] KotlinParser.ClassParameterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.classParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassParameter([NotNull] KotlinParser.ClassParameterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.delegationSpecifiers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDelegationSpecifiers([NotNull] KotlinParser.DelegationSpecifiersContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.delegationSpecifiers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDelegationSpecifiers([NotNull] KotlinParser.DelegationSpecifiersContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.delegationSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDelegationSpecifier([NotNull] KotlinParser.DelegationSpecifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.delegationSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDelegationSpecifier([NotNull] KotlinParser.DelegationSpecifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.constructorInvocation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstructorInvocation([NotNull] KotlinParser.ConstructorInvocationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.constructorInvocation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstructorInvocation([NotNull] KotlinParser.ConstructorInvocationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.annotatedDelegationSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAnnotatedDelegationSpecifier([NotNull] KotlinParser.AnnotatedDelegationSpecifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.annotatedDelegationSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAnnotatedDelegationSpecifier([NotNull] KotlinParser.AnnotatedDelegationSpecifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.explicitDelegation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExplicitDelegation([NotNull] KotlinParser.ExplicitDelegationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.explicitDelegation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExplicitDelegation([NotNull] KotlinParser.ExplicitDelegationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.typeParameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeParameters([NotNull] KotlinParser.TypeParametersContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.typeParameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeParameters([NotNull] KotlinParser.TypeParametersContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.typeParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeParameter([NotNull] KotlinParser.TypeParameterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.typeParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeParameter([NotNull] KotlinParser.TypeParameterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.typeConstraints"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeConstraints([NotNull] KotlinParser.TypeConstraintsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.typeConstraints"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeConstraints([NotNull] KotlinParser.TypeConstraintsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.typeConstraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeConstraint([NotNull] KotlinParser.TypeConstraintContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.typeConstraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeConstraint([NotNull] KotlinParser.TypeConstraintContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.classMemberDeclarations"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassMemberDeclarations([NotNull] KotlinParser.ClassMemberDeclarationsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.classMemberDeclarations"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassMemberDeclarations([NotNull] KotlinParser.ClassMemberDeclarationsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.classMemberDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassMemberDeclaration([NotNull] KotlinParser.ClassMemberDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.classMemberDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassMemberDeclaration([NotNull] KotlinParser.ClassMemberDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.anonymousInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAnonymousInitializer([NotNull] KotlinParser.AnonymousInitializerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.anonymousInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAnonymousInitializer([NotNull] KotlinParser.AnonymousInitializerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.companionObject"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCompanionObject([NotNull] KotlinParser.CompanionObjectContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.companionObject"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCompanionObject([NotNull] KotlinParser.CompanionObjectContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.functionValueParameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionValueParameters([NotNull] KotlinParser.FunctionValueParametersContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.functionValueParameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionValueParameters([NotNull] KotlinParser.FunctionValueParametersContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.functionValueParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionValueParameter([NotNull] KotlinParser.FunctionValueParameterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.functionValueParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionValueParameter([NotNull] KotlinParser.FunctionValueParameterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.functionDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionDeclaration([NotNull] KotlinParser.FunctionDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.functionDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionDeclaration([NotNull] KotlinParser.FunctionDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.functionBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionBody([NotNull] KotlinParser.FunctionBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.functionBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionBody([NotNull] KotlinParser.FunctionBodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.variableDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariableDeclaration([NotNull] KotlinParser.VariableDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.variableDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariableDeclaration([NotNull] KotlinParser.VariableDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.multiVariableDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMultiVariableDeclaration([NotNull] KotlinParser.MultiVariableDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.multiVariableDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMultiVariableDeclaration([NotNull] KotlinParser.MultiVariableDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.propertyDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPropertyDeclaration([NotNull] KotlinParser.PropertyDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.propertyDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPropertyDeclaration([NotNull] KotlinParser.PropertyDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.propertyDelegate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPropertyDelegate([NotNull] KotlinParser.PropertyDelegateContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.propertyDelegate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPropertyDelegate([NotNull] KotlinParser.PropertyDelegateContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.getter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGetter([NotNull] KotlinParser.GetterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.getter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGetter([NotNull] KotlinParser.GetterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.setter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSetter([NotNull] KotlinParser.SetterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.setter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSetter([NotNull] KotlinParser.SetterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.parametersWithOptionalType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParametersWithOptionalType([NotNull] KotlinParser.ParametersWithOptionalTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.parametersWithOptionalType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParametersWithOptionalType([NotNull] KotlinParser.ParametersWithOptionalTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.functionValueParameterWithOptionalType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionValueParameterWithOptionalType([NotNull] KotlinParser.FunctionValueParameterWithOptionalTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.functionValueParameterWithOptionalType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionValueParameterWithOptionalType([NotNull] KotlinParser.FunctionValueParameterWithOptionalTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.parameterWithOptionalType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameterWithOptionalType([NotNull] KotlinParser.ParameterWithOptionalTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.parameterWithOptionalType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameterWithOptionalType([NotNull] KotlinParser.ParameterWithOptionalTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameter([NotNull] KotlinParser.ParameterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameter([NotNull] KotlinParser.ParameterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.objectDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObjectDeclaration([NotNull] KotlinParser.ObjectDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.objectDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObjectDeclaration([NotNull] KotlinParser.ObjectDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.secondaryConstructor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSecondaryConstructor([NotNull] KotlinParser.SecondaryConstructorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.secondaryConstructor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSecondaryConstructor([NotNull] KotlinParser.SecondaryConstructorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.constructorDelegationCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstructorDelegationCall([NotNull] KotlinParser.ConstructorDelegationCallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.constructorDelegationCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstructorDelegationCall([NotNull] KotlinParser.ConstructorDelegationCallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.enumClassBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumClassBody([NotNull] KotlinParser.EnumClassBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.enumClassBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumClassBody([NotNull] KotlinParser.EnumClassBodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.enumEntries"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumEntries([NotNull] KotlinParser.EnumEntriesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.enumEntries"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumEntries([NotNull] KotlinParser.EnumEntriesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.enumEntry"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumEntry([NotNull] KotlinParser.EnumEntryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.enumEntry"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumEntry([NotNull] KotlinParser.EnumEntryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType([NotNull] KotlinParser.TypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType([NotNull] KotlinParser.TypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.typeReference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeReference([NotNull] KotlinParser.TypeReferenceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.typeReference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeReference([NotNull] KotlinParser.TypeReferenceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.nullableType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNullableType([NotNull] KotlinParser.NullableTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.nullableType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNullableType([NotNull] KotlinParser.NullableTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.quest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQuest([NotNull] KotlinParser.QuestContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.quest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQuest([NotNull] KotlinParser.QuestContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.userType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUserType([NotNull] KotlinParser.UserTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.userType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUserType([NotNull] KotlinParser.UserTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.simpleUserType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSimpleUserType([NotNull] KotlinParser.SimpleUserTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.simpleUserType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSimpleUserType([NotNull] KotlinParser.SimpleUserTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.typeProjection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeProjection([NotNull] KotlinParser.TypeProjectionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.typeProjection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeProjection([NotNull] KotlinParser.TypeProjectionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.typeProjectionModifiers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeProjectionModifiers([NotNull] KotlinParser.TypeProjectionModifiersContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.typeProjectionModifiers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeProjectionModifiers([NotNull] KotlinParser.TypeProjectionModifiersContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.typeProjectionModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeProjectionModifier([NotNull] KotlinParser.TypeProjectionModifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.typeProjectionModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeProjectionModifier([NotNull] KotlinParser.TypeProjectionModifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.functionType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionType([NotNull] KotlinParser.FunctionTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.functionType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionType([NotNull] KotlinParser.FunctionTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.functionTypeParameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionTypeParameters([NotNull] KotlinParser.FunctionTypeParametersContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.functionTypeParameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionTypeParameters([NotNull] KotlinParser.FunctionTypeParametersContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.parenthesizedType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParenthesizedType([NotNull] KotlinParser.ParenthesizedTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.parenthesizedType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParenthesizedType([NotNull] KotlinParser.ParenthesizedTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.receiverType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReceiverType([NotNull] KotlinParser.ReceiverTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.receiverType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReceiverType([NotNull] KotlinParser.ReceiverTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.parenthesizedUserType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParenthesizedUserType([NotNull] KotlinParser.ParenthesizedUserTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.parenthesizedUserType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParenthesizedUserType([NotNull] KotlinParser.ParenthesizedUserTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.definitelyNonNullableType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDefinitelyNonNullableType([NotNull] KotlinParser.DefinitelyNonNullableTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.definitelyNonNullableType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDefinitelyNonNullableType([NotNull] KotlinParser.DefinitelyNonNullableTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.statements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatements([NotNull] KotlinParser.StatementsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.statements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatements([NotNull] KotlinParser.StatementsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] KotlinParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] KotlinParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.label"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLabel([NotNull] KotlinParser.LabelContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.label"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLabel([NotNull] KotlinParser.LabelContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.controlStructureBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterControlStructureBody([NotNull] KotlinParser.ControlStructureBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.controlStructureBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitControlStructureBody([NotNull] KotlinParser.ControlStructureBodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlock([NotNull] KotlinParser.BlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlock([NotNull] KotlinParser.BlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.loopStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLoopStatement([NotNull] KotlinParser.LoopStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.loopStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLoopStatement([NotNull] KotlinParser.LoopStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.forStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForStatement([NotNull] KotlinParser.ForStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.forStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForStatement([NotNull] KotlinParser.ForStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.whileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhileStatement([NotNull] KotlinParser.WhileStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.whileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhileStatement([NotNull] KotlinParser.WhileStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.doWhileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDoWhileStatement([NotNull] KotlinParser.DoWhileStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.doWhileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDoWhileStatement([NotNull] KotlinParser.DoWhileStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignment([NotNull] KotlinParser.AssignmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignment([NotNull] KotlinParser.AssignmentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.semi"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSemi([NotNull] KotlinParser.SemiContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.semi"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSemi([NotNull] KotlinParser.SemiContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.semis"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSemis([NotNull] KotlinParser.SemisContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.semis"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSemis([NotNull] KotlinParser.SemisContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] KotlinParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] KotlinParser.ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.disjunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDisjunction([NotNull] KotlinParser.DisjunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.disjunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDisjunction([NotNull] KotlinParser.DisjunctionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.conjunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConjunction([NotNull] KotlinParser.ConjunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.conjunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConjunction([NotNull] KotlinParser.ConjunctionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.equality"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEquality([NotNull] KotlinParser.EqualityContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.equality"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEquality([NotNull] KotlinParser.EqualityContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.comparison"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComparison([NotNull] KotlinParser.ComparisonContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.comparison"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComparison([NotNull] KotlinParser.ComparisonContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.genericCallLikeComparison"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGenericCallLikeComparison([NotNull] KotlinParser.GenericCallLikeComparisonContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.genericCallLikeComparison"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGenericCallLikeComparison([NotNull] KotlinParser.GenericCallLikeComparisonContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.infixOperation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInfixOperation([NotNull] KotlinParser.InfixOperationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.infixOperation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInfixOperation([NotNull] KotlinParser.InfixOperationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.elvisExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElvisExpression([NotNull] KotlinParser.ElvisExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.elvisExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElvisExpression([NotNull] KotlinParser.ElvisExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.elvis"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElvis([NotNull] KotlinParser.ElvisContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.elvis"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElvis([NotNull] KotlinParser.ElvisContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.infixFunctionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInfixFunctionCall([NotNull] KotlinParser.InfixFunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.infixFunctionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInfixFunctionCall([NotNull] KotlinParser.InfixFunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.rangeExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRangeExpression([NotNull] KotlinParser.RangeExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.rangeExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRangeExpression([NotNull] KotlinParser.RangeExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.additiveExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAdditiveExpression([NotNull] KotlinParser.AdditiveExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.additiveExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAdditiveExpression([NotNull] KotlinParser.AdditiveExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.multiplicativeExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMultiplicativeExpression([NotNull] KotlinParser.MultiplicativeExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.multiplicativeExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMultiplicativeExpression([NotNull] KotlinParser.MultiplicativeExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.asExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAsExpression([NotNull] KotlinParser.AsExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.asExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAsExpression([NotNull] KotlinParser.AsExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.prefixUnaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrefixUnaryExpression([NotNull] KotlinParser.PrefixUnaryExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.prefixUnaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrefixUnaryExpression([NotNull] KotlinParser.PrefixUnaryExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.unaryPrefix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnaryPrefix([NotNull] KotlinParser.UnaryPrefixContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.unaryPrefix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnaryPrefix([NotNull] KotlinParser.UnaryPrefixContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.postfixUnaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPostfixUnaryExpression([NotNull] KotlinParser.PostfixUnaryExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.postfixUnaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPostfixUnaryExpression([NotNull] KotlinParser.PostfixUnaryExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.postfixUnarySuffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPostfixUnarySuffix([NotNull] KotlinParser.PostfixUnarySuffixContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.postfixUnarySuffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPostfixUnarySuffix([NotNull] KotlinParser.PostfixUnarySuffixContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.directlyAssignableExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDirectlyAssignableExpression([NotNull] KotlinParser.DirectlyAssignableExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.directlyAssignableExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDirectlyAssignableExpression([NotNull] KotlinParser.DirectlyAssignableExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.parenthesizedDirectlyAssignableExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParenthesizedDirectlyAssignableExpression([NotNull] KotlinParser.ParenthesizedDirectlyAssignableExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.parenthesizedDirectlyAssignableExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParenthesizedDirectlyAssignableExpression([NotNull] KotlinParser.ParenthesizedDirectlyAssignableExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.assignableExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignableExpression([NotNull] KotlinParser.AssignableExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.assignableExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignableExpression([NotNull] KotlinParser.AssignableExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.parenthesizedAssignableExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParenthesizedAssignableExpression([NotNull] KotlinParser.ParenthesizedAssignableExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.parenthesizedAssignableExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParenthesizedAssignableExpression([NotNull] KotlinParser.ParenthesizedAssignableExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.assignableSuffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignableSuffix([NotNull] KotlinParser.AssignableSuffixContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.assignableSuffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignableSuffix([NotNull] KotlinParser.AssignableSuffixContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.indexingSuffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIndexingSuffix([NotNull] KotlinParser.IndexingSuffixContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.indexingSuffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIndexingSuffix([NotNull] KotlinParser.IndexingSuffixContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.navigationSuffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNavigationSuffix([NotNull] KotlinParser.NavigationSuffixContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.navigationSuffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNavigationSuffix([NotNull] KotlinParser.NavigationSuffixContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.callSuffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCallSuffix([NotNull] KotlinParser.CallSuffixContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.callSuffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCallSuffix([NotNull] KotlinParser.CallSuffixContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.annotatedLambda"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAnnotatedLambda([NotNull] KotlinParser.AnnotatedLambdaContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.annotatedLambda"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAnnotatedLambda([NotNull] KotlinParser.AnnotatedLambdaContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.typeArguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeArguments([NotNull] KotlinParser.TypeArgumentsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.typeArguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeArguments([NotNull] KotlinParser.TypeArgumentsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.valueArguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValueArguments([NotNull] KotlinParser.ValueArgumentsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.valueArguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValueArguments([NotNull] KotlinParser.ValueArgumentsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.valueArgument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValueArgument([NotNull] KotlinParser.ValueArgumentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.valueArgument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValueArgument([NotNull] KotlinParser.ValueArgumentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.primaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimaryExpression([NotNull] KotlinParser.PrimaryExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.primaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimaryExpression([NotNull] KotlinParser.PrimaryExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.parenthesizedExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParenthesizedExpression([NotNull] KotlinParser.ParenthesizedExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.parenthesizedExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParenthesizedExpression([NotNull] KotlinParser.ParenthesizedExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.collectionLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCollectionLiteral([NotNull] KotlinParser.CollectionLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.collectionLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCollectionLiteral([NotNull] KotlinParser.CollectionLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.literalConstant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLiteralConstant([NotNull] KotlinParser.LiteralConstantContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.literalConstant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLiteralConstant([NotNull] KotlinParser.LiteralConstantContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.stringLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStringLiteral([NotNull] KotlinParser.StringLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.stringLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStringLiteral([NotNull] KotlinParser.StringLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.lineStringLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLineStringLiteral([NotNull] KotlinParser.LineStringLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.lineStringLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLineStringLiteral([NotNull] KotlinParser.LineStringLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.multiLineStringLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMultiLineStringLiteral([NotNull] KotlinParser.MultiLineStringLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.multiLineStringLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMultiLineStringLiteral([NotNull] KotlinParser.MultiLineStringLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.lineStringContent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLineStringContent([NotNull] KotlinParser.LineStringContentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.lineStringContent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLineStringContent([NotNull] KotlinParser.LineStringContentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.lineStringExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLineStringExpression([NotNull] KotlinParser.LineStringExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.lineStringExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLineStringExpression([NotNull] KotlinParser.LineStringExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.multiLineStringContent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMultiLineStringContent([NotNull] KotlinParser.MultiLineStringContentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.multiLineStringContent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMultiLineStringContent([NotNull] KotlinParser.MultiLineStringContentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.multiLineStringExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMultiLineStringExpression([NotNull] KotlinParser.MultiLineStringExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.multiLineStringExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMultiLineStringExpression([NotNull] KotlinParser.MultiLineStringExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.lambdaLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLambdaLiteral([NotNull] KotlinParser.LambdaLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.lambdaLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLambdaLiteral([NotNull] KotlinParser.LambdaLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.lambdaParameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLambdaParameters([NotNull] KotlinParser.LambdaParametersContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.lambdaParameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLambdaParameters([NotNull] KotlinParser.LambdaParametersContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.lambdaParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLambdaParameter([NotNull] KotlinParser.LambdaParameterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.lambdaParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLambdaParameter([NotNull] KotlinParser.LambdaParameterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.anonymousFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAnonymousFunction([NotNull] KotlinParser.AnonymousFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.anonymousFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAnonymousFunction([NotNull] KotlinParser.AnonymousFunctionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.functionLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionLiteral([NotNull] KotlinParser.FunctionLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.functionLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionLiteral([NotNull] KotlinParser.FunctionLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.objectLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObjectLiteral([NotNull] KotlinParser.ObjectLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.objectLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObjectLiteral([NotNull] KotlinParser.ObjectLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.thisExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterThisExpression([NotNull] KotlinParser.ThisExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.thisExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitThisExpression([NotNull] KotlinParser.ThisExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.superExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSuperExpression([NotNull] KotlinParser.SuperExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.superExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSuperExpression([NotNull] KotlinParser.SuperExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.ifExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfExpression([NotNull] KotlinParser.IfExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.ifExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfExpression([NotNull] KotlinParser.IfExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.whenSubject"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhenSubject([NotNull] KotlinParser.WhenSubjectContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.whenSubject"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhenSubject([NotNull] KotlinParser.WhenSubjectContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.whenExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhenExpression([NotNull] KotlinParser.WhenExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.whenExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhenExpression([NotNull] KotlinParser.WhenExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.whenEntry"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhenEntry([NotNull] KotlinParser.WhenEntryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.whenEntry"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhenEntry([NotNull] KotlinParser.WhenEntryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.whenCondition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhenCondition([NotNull] KotlinParser.WhenConditionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.whenCondition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhenCondition([NotNull] KotlinParser.WhenConditionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.rangeTest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRangeTest([NotNull] KotlinParser.RangeTestContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.rangeTest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRangeTest([NotNull] KotlinParser.RangeTestContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.typeTest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeTest([NotNull] KotlinParser.TypeTestContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.typeTest"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeTest([NotNull] KotlinParser.TypeTestContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.tryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTryExpression([NotNull] KotlinParser.TryExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.tryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTryExpression([NotNull] KotlinParser.TryExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.catchBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCatchBlock([NotNull] KotlinParser.CatchBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.catchBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCatchBlock([NotNull] KotlinParser.CatchBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.finallyBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFinallyBlock([NotNull] KotlinParser.FinallyBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.finallyBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFinallyBlock([NotNull] KotlinParser.FinallyBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.jumpExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJumpExpression([NotNull] KotlinParser.JumpExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.jumpExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJumpExpression([NotNull] KotlinParser.JumpExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.callableReference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCallableReference([NotNull] KotlinParser.CallableReferenceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.callableReference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCallableReference([NotNull] KotlinParser.CallableReferenceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.assignmentAndOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignmentAndOperator([NotNull] KotlinParser.AssignmentAndOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.assignmentAndOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignmentAndOperator([NotNull] KotlinParser.AssignmentAndOperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.equalityOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEqualityOperator([NotNull] KotlinParser.EqualityOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.equalityOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEqualityOperator([NotNull] KotlinParser.EqualityOperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.comparisonOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComparisonOperator([NotNull] KotlinParser.ComparisonOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.comparisonOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComparisonOperator([NotNull] KotlinParser.ComparisonOperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.inOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInOperator([NotNull] KotlinParser.InOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.inOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInOperator([NotNull] KotlinParser.InOperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.isOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIsOperator([NotNull] KotlinParser.IsOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.isOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIsOperator([NotNull] KotlinParser.IsOperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.additiveOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAdditiveOperator([NotNull] KotlinParser.AdditiveOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.additiveOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAdditiveOperator([NotNull] KotlinParser.AdditiveOperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.multiplicativeOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMultiplicativeOperator([NotNull] KotlinParser.MultiplicativeOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.multiplicativeOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMultiplicativeOperator([NotNull] KotlinParser.MultiplicativeOperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.asOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAsOperator([NotNull] KotlinParser.AsOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.asOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAsOperator([NotNull] KotlinParser.AsOperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.prefixUnaryOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrefixUnaryOperator([NotNull] KotlinParser.PrefixUnaryOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.prefixUnaryOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrefixUnaryOperator([NotNull] KotlinParser.PrefixUnaryOperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.postfixUnaryOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPostfixUnaryOperator([NotNull] KotlinParser.PostfixUnaryOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.postfixUnaryOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPostfixUnaryOperator([NotNull] KotlinParser.PostfixUnaryOperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.excl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExcl([NotNull] KotlinParser.ExclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.excl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExcl([NotNull] KotlinParser.ExclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.memberAccessOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMemberAccessOperator([NotNull] KotlinParser.MemberAccessOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.memberAccessOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMemberAccessOperator([NotNull] KotlinParser.MemberAccessOperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.safeNav"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSafeNav([NotNull] KotlinParser.SafeNavContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.safeNav"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSafeNav([NotNull] KotlinParser.SafeNavContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.modifiers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModifiers([NotNull] KotlinParser.ModifiersContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.modifiers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModifiers([NotNull] KotlinParser.ModifiersContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.parameterModifiers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameterModifiers([NotNull] KotlinParser.ParameterModifiersContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.parameterModifiers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameterModifiers([NotNull] KotlinParser.ParameterModifiersContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.modifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModifier([NotNull] KotlinParser.ModifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.modifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModifier([NotNull] KotlinParser.ModifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.typeModifiers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeModifiers([NotNull] KotlinParser.TypeModifiersContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.typeModifiers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeModifiers([NotNull] KotlinParser.TypeModifiersContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.typeModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeModifier([NotNull] KotlinParser.TypeModifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.typeModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeModifier([NotNull] KotlinParser.TypeModifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.classModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassModifier([NotNull] KotlinParser.ClassModifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.classModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassModifier([NotNull] KotlinParser.ClassModifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.memberModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMemberModifier([NotNull] KotlinParser.MemberModifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.memberModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMemberModifier([NotNull] KotlinParser.MemberModifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.visibilityModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVisibilityModifier([NotNull] KotlinParser.VisibilityModifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.visibilityModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVisibilityModifier([NotNull] KotlinParser.VisibilityModifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.varianceModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarianceModifier([NotNull] KotlinParser.VarianceModifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.varianceModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarianceModifier([NotNull] KotlinParser.VarianceModifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.typeParameterModifiers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeParameterModifiers([NotNull] KotlinParser.TypeParameterModifiersContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.typeParameterModifiers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeParameterModifiers([NotNull] KotlinParser.TypeParameterModifiersContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.typeParameterModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeParameterModifier([NotNull] KotlinParser.TypeParameterModifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.typeParameterModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeParameterModifier([NotNull] KotlinParser.TypeParameterModifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.functionModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionModifier([NotNull] KotlinParser.FunctionModifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.functionModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionModifier([NotNull] KotlinParser.FunctionModifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.propertyModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPropertyModifier([NotNull] KotlinParser.PropertyModifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.propertyModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPropertyModifier([NotNull] KotlinParser.PropertyModifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.inheritanceModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInheritanceModifier([NotNull] KotlinParser.InheritanceModifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.inheritanceModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInheritanceModifier([NotNull] KotlinParser.InheritanceModifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.parameterModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameterModifier([NotNull] KotlinParser.ParameterModifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.parameterModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameterModifier([NotNull] KotlinParser.ParameterModifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.reificationModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReificationModifier([NotNull] KotlinParser.ReificationModifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.reificationModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReificationModifier([NotNull] KotlinParser.ReificationModifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.platformModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPlatformModifier([NotNull] KotlinParser.PlatformModifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.platformModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPlatformModifier([NotNull] KotlinParser.PlatformModifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.annotation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAnnotation([NotNull] KotlinParser.AnnotationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.annotation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAnnotation([NotNull] KotlinParser.AnnotationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.singleAnnotation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSingleAnnotation([NotNull] KotlinParser.SingleAnnotationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.singleAnnotation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSingleAnnotation([NotNull] KotlinParser.SingleAnnotationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.multiAnnotation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMultiAnnotation([NotNull] KotlinParser.MultiAnnotationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.multiAnnotation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMultiAnnotation([NotNull] KotlinParser.MultiAnnotationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.annotationUseSiteTarget"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAnnotationUseSiteTarget([NotNull] KotlinParser.AnnotationUseSiteTargetContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.annotationUseSiteTarget"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAnnotationUseSiteTarget([NotNull] KotlinParser.AnnotationUseSiteTargetContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.unescapedAnnotation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnescapedAnnotation([NotNull] KotlinParser.UnescapedAnnotationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.unescapedAnnotation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnescapedAnnotation([NotNull] KotlinParser.UnescapedAnnotationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.simpleIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSimpleIdentifier([NotNull] KotlinParser.SimpleIdentifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.simpleIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSimpleIdentifier([NotNull] KotlinParser.SimpleIdentifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="KotlinParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdentifier([NotNull] KotlinParser.IdentifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="KotlinParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdentifier([NotNull] KotlinParser.IdentifierContext context);
}
} // namespace CobbleBuild.Kotlin
